name: CI

permissions:
  contents: read

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  rustup_toolchain: stable
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/act-rustup
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{env.rustup_toolchain}}
          components: rustfmt
      - run: cargo fmt --all --check

  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    if: ${{ github.event.act || github.ref == 'refs/heads/master' }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/act-rustup
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{env.rustup_toolchain}}
          components: clippy
      - name: Clippy
        run: cargo clippy --all-features --locked -- -D warnings

  cargo-test:
    name: cargo test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # pyo3 error: linking with `cc` failed: exit status: 1
          # - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.act || github.ref == 'refs/heads/master' }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/act-rustup
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{env.rustup_toolchain}}
      - run: cargo test --all-features
